project_id = "jrjfrwraacgecrrsxshy"

[functions.parse-syllabus]
verify_jwt = true

[functions.chat-tutor]
verify_jwt = true

[functions.send-pinky-reminders]
verify_jwt = false

[functions.create-demo-posts]
verify_jwt = true

[functions.class-tutor]
verify_jwt = true
